#!/usr/bin/env bash
# 0-world_wide_web --script to display info about subdomains


domain_info() {
if [ "$2" ];
then
    echo -n "The subdomain $2 is a"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print " " $4 " record and points to "$5}' | tail -n 1
else
    for  domain_info in www lb-01 web-01 web-02 
    do
        echo -n "The subdomain $domain_info is a"
        dig "$domain_info.$1" | grep -A1 'ANSWER SECTION:' | awk '{print " " $4 " record and points to "$5}' | tail -n 1
    done
fi
}
domain_info "$1" "$2"
