#!/usr/bin/env bash
# Installs and configure HAproxy on my lb-01 server.

sudo apt update
sudo apt-get install -y haproxy

# Let Haproxy be able to be managed using init script


confi=\
"
backend web-backend
	balance roundrobin
	server 84732-web-01 34.207.64.191:80 check
	server 84732-web-02 54.90.28.71:80 check
	mode http
frontend http
	bind *:80
	mode http
	default_backend web-backend
"

echo "$confi" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart

