#!/usr/bin/env bash
# Installs and configure HAproxy on my lb-01 server.

sudo apt update
sudo apt-get install -y haproxy

# Let Haproxy be able to be managed using init script
sudo  echo "ENABLED=1" | sudo tee -a "/etc/default/haproxy"
sudo printf "\nlisten www\n\tbind :80\n\tmode http\n\tstats enable\n\tstats uri /haproxy?status\n\tbalance roundrobin\n\tserver 84732-web-01 34.207.64.191:80 check\n\tserver 84732-web-02 54.90.28.71:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
