#!/usr/bin/env bash
#To debug the issue of Nginx server  not listening on port 80
sudo apt update
sudo apt install nginx -y

# Ensure Nginx is running
sudo service start nginx
sudo service enable nginx   
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart

