#!/usr/bin/env bash
# Here is a short and sweet Bash script that will configure a server to listen on port 80
#!/usr/bin/env bash
# Command to make an nginx server listen on port 80, shorter version
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
pkill -1 nginx
