#!/usr/bin/env bash
#Install ufw firewall:

sudo apt-get update
sudo apt-get install ufw

sudo ufw disable
#allow all outgoing trafic
sudo ufw default allow outgoing
# Block all incoming traffic:

sudo ufw default deny incoming


# Allow incoming traffic on SSH, HTTPS SSL and HTTP:

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp


# Enable ufw:

sudo ufw enable



